# Site settings
title: Lectures
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lectures.pascallaliberte.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
